server:
  port: 8085

spring:
  application:
    name: ticket-worker-service
  
  # 데이터베이스 연결 설정 (ticket-service와 완벽히 동일하게 수정!)
  datasource:
    url: jdbc:postgresql://localhost:5432/baseball_platform
    username: baseball
    password: baseball
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:               # <--- 여기서부터 추가
      hibernate:
        hbm2ddl:
          create_namespaces: true

  # SQS (Spring Cloud AWS) 연결 설정
  cloud:
    aws:
      region:
        static: ap-northeast-2
      sqs:
        endpoint: ${SPRING_CLOUD_AWS_SQS_ENDPOINT:http://localhost:9324}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
