server:
  port: 8087

spring:
  application:
    name: ticket-service

  datasource:
    url: jdbc:postgresql://localhost:5432/baseball_platform
    username: baseball
    password: baseball
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    aws:
      region:
        static: ap-northeast-2
      sqs:
        endpoint: ${SPRING_CLOUD_AWS_SQS_ENDPOINT:http://localhost:9324}
