name: ticket-worker-service CI/CD

on:
  push:
    branches: [ main, feature/ci-cd ]
    paths:
      - 'ticket-worker-service/**'
      - '.github/workflows/ticket-worker-service.yml'

env:
  SERVICE_NAME: ticket-worker-service
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: AWS 로그인
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ECR 로그인
        uses: aws-actions/amazon-ecr-login@v2

      - name: 도커 이미지 빌드 & ECR 푸시
        run: |
          docker build \
            -f ./ticket-worker-service/Dockerfile \
            -t ${{ env.ECR_REGISTRY }}/dev-ticket-worker-service:${{ github.sha }} \
            .
          docker push ${{ env.ECR_REGISTRY }}/dev-ticket-worker-service:${{ github.sha }}

      - name: kustomize 설치
        if: github.ref == 'refs/heads/main'
        uses: imranismail/setup-kustomize@v2

      - name: GitOps 이미지 태그 업데이트
        if: github.ref == 'refs/heads/main'
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/baselink-msa/git-ops.git
          cd git-ops/overlays/dev

          kustomize edit set image ticket-worker-service=${{ env.ECR_REGISTRY }}/dev-ticket-worker-service:${{ github.sha }}

          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "deploy: update ticket-worker-service to ${{ github.sha }}"
          git push

